# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Title Goes Here
tagline:             'Mostly engineering'
description:         'Posts on assorted data science and engineering topics.'
url:                 http://maciejkula.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Maciej Kula
  url:               https://twitter.com/Maciej_Kula
  email:             

# Custom vars
version:             1.0.0
